version: '3'
services:
  datadog-java-log:
    image: datadog-java-log:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    #labels:
      #com.datadoghq.ad.logs: '[<LOGS_CONFIG>]'
  datadog-agent:
    image: datadog/agent:latest
    pid: host
    environment:
     - DD_API_KEY=13debfd9369ad3d6f41539d34b6056c3
     - DD_SITE=datadoghq.com
     - DD_LOGS_ENABLED=true
     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
     - DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  